version: '2.1'

orbs:
  megalinter: relativesure/megalinter@2.1.1

workflows:
  run-megalinter:
    jobs:
      - megalinter/run:
          context:
            # Uncomment for RelativeSure
            #- "Main Context"
            # For KubeArchitect
            - main-context
